aspnet/Localization

src/Microsoft.Framework.Localization.Abstractions/IStringLocalizerExtensions.cs, src/Microsoft.Framework.Localization.Abstractions/StringLocalizerExtensions.cs, src/Microsoft.Framework.Localization/ResourceManagerStringLocalizer.cs, src/Microsoft.Framework.Localization/ResourceManagerWithCultureStringLocalizer.cs
@Eilon had mentioned he thought having both the indexers and get methods on the `IStringLocalizer` interface was overkill so I've changed the get methods to be extension methods instead.
=> Moved methods off of IStringLocalizer and into extension methods

src/Microsoft.Framework.Localization.Abstractions/IStringLocalizer.cs, src/Microsoft.Framework.Localization.Abstractions/StringLocalizerExtensions.cs, src/Microsoft.Framework.Localization.Abstractions/StringLocalizerOfT.cs, src/Microsoft.Framework.Localization/ResourceManagerStringLocalizer.cs, src/Microsoft.Framework.Localization/ResourceManagerWithCultureStringLocalizer.cs, test/Microsoft.Framework.Localization.Test/ResourceManagerStringLocalizerTest.cs
=> Add IStringLocalizer.GetAllStrings method

src/Microsoft.Framework.Localization/Properties/AssemblyInfo.cs
Fix project name ```Microsoft.Framework.Localization.Tests``` in AssemblyInfo.cs
/cc @kirthik @Eilon
=> Fix project name in AssemblyInfo

test/Microsoft.AspNet.Localization.FunctionalTests/LocalizationTest.cs
This change fixes test break on Mac. In short, the test requires deploying a server on Mono shouldn't be run when the current runtime framework is CoreCLR. Because in that case the path to the mono runtime can't be found on `$PATH`.
The change simply split one `theroy` into two and run under different runtime. The build script is responsible of running test on each framework, which it does today.
/cc @kirthik @cesarbs
=> Run CoreCLR test when runtime framework is CoreCLR

src/Microsoft.Extensions.Localization/ResourceManagerStringLocalizer.cs
Make ResourceManagerStringLocalizer thread safe now instances are cached & shared
@Eilon @ryanbrandenburg
=> Make ResourceManagerStringLocalizer thread safe

samples/LocalizationSample/Startup.cs, src/Microsoft.AspNet.Localization/ApplicationBuilderExtensions.cs, src/Microsoft.AspNet.Localization/RequestLocalizationMiddleware.cs, src/Microsoft.AspNet.Localization/RequestLocalizationOptions.cs, test/LocalizationWebsite/StartupResourcesAtRootFolder.cs, test/LocalizationWebsite/StartupResourcesInFolder.cs, test/Microsoft.AspNet.Localization.Tests/AcceptLanguageHeaderRequestCultureProviderTest.cs, test/Microsoft.AspNet.Localization.Tests/CookieRequestCultureProviderTest.cs, test/Microsoft.AspNet.Localization.Tests/CustomRequestCultureProviderTest.cs, test/Microsoft.AspNet.Localization.Tests/QueryStringRequestCultureProviderTest.cs, test/Microsoft.AspNet.Localization.Tests/RequestLocalizationOptionsTest.cs
#164 
Fixed up some out of date doc comments too.
@rynowak @ryanbrandenburg @Eilon
=> Improve usability of the request localization middleware #164

src/Microsoft.AspNet.Localization/RequestLocalizationMiddleware.cs, src/Microsoft.AspNet.Localization/RequestLocalizationOptions.cs, test/Microsoft.AspNet.Localization.FunctionalTests/LocalizationTest.cs
- Enabled by default and configred by `RequestLocalizationOptions.FallbackToAncestorCulture`/`FallbackToAncestorUICulture`
- Tries all candidate cultures first before trimming the list to parents and trying again (breadth first), until a match is found or none is found
- Updated functional tests to cover fallback case
- #112
@ryanbrandenburg @Eilon @rynowak @lodejard
=> Added support for hierarchical culture fallback

src/Microsoft.AspNet.Localization/RequestLocalizationMiddleware.cs, src/Microsoft.AspNet.Localization/RequestLocalizationOptions.cs
After talking to some folks we think depth-first is a better approach here (i.e. more useful).
@lodejard @ryanbrandenburg @rynowak @miloush
#112
=> Change culture fallback to depth-first

test/Microsoft.AspNetCore.Localization.FunctionalTests/LocalizationSampleTest.cs, test/Microsoft.AspNetCore.Localization.FunctionalTests/LocalizationTest.cs, test/Microsoft.AspNetCore.Localization.FunctionalTests/TestRunner.cs
This will fix the full framework tests launched on Mono. The relative paths were broken since we disable app domains and need to resolve paths from xunit.runner.exe. Resolving from the repo root folder is more robust.
cc @pranavkm @BrennanConroy
=> Resolve test application paths more robustly

src/Microsoft.Extensions.Localization/Internal/AssemblyResourceStringProvider.cs, src/Microsoft.Extensions.Localization/Internal/IResourceStringProvider.cs, src/Microsoft.Extensions.Localization/ResourceManagerStringLocalizer.cs, src/Microsoft.Extensions.Localization/ResourceManagerWithCultureStringLocalizer.cs, test/Microsoft.Extensions.Localization.Tests/ResourceManagerStringLocalizerTest.cs
@rynowak here is my experiment in abstracting the management of resource strings properly.
I was wondering if maybe the interface should actually be for the strings instead of a stream since what we'd like to have as a final fix for this is a corefx API which would give us all the strings for a culture, rather than a stream.
=> Get all string experiment

src/Microsoft.AspNetCore.Localization/RequestLocalizationMiddleware.cs, src/Microsoft.Extensions.Globalization.CultureInfoCache/CultureInfoCache.cs, test/LocalizationWebsite/StartupCustomCulturePreserved.cs, test/LocalizationWebsite/project.json, test/Microsoft.AspNetCore.Localization.FunctionalTests/LocalizationTest.cs
Fixes #203. Given this fix `CultureInfoCache` could just as a easily be a helper function on the middleware since it's no longer an actual cache, but I wasn't sure if we would be able to get rid of the whole class like that. @DamianEdwards would that be possible?
=> Use existing CultureInfo

src/Microsoft.Extensions.Localization/ResourceManagerStringLocalizer.cs
This PR is intended to fix #297 by adding the `AssemblyWrapper` constructor back to `ResourcemanagerStringLocalizer`. It keeps the `IResourceStringProvider` constructor so that we don't have to rewrite all the tests, but if that's not ok I can remove it and see about reworking them.
=> Fix breaking change

src/Microsoft.Extensions.Localization/ResourceManagerStringLocalizer.cs
After the PR #299 I notice there's some unnecessary lines of code, also there's an extra check from awhile [here](https://github.com/aspnet/Localization/blob/dev/src/Microsoft.Extensions.Localization/ResourceManagerStringLocalizer.cs#L48) because the `AssemblyWrapper` is already perform this check
/cc @Eilon @ryanbrandenburg
=> Remove unnecessary code in ResourceManagerStringLocalizer

src/Microsoft.Extensions.Localization.Abstractions/LocalizedString.cs
The docs for `ResourceNotFound` is little bit confusing, it should set to `true` if the string is missing and alternative string value was used
=> Fix LocalizeString docs

src/Microsoft.AspNetCore.Localization.Routing/baseline.net45.json, src/Microsoft.AspNetCore.Localization.Routing/baseline.netcore.json
`Microsoft.AspNetCore.Localization.Routing` was missing baselines so I added some based off the 1.1.0 release.
=> Add baselines to Microsoft.AspNetCore.Localization.Routing

samples/LocalizationSample/LocalizationSample.csproj, test/LocalizationWebsite/LocalizationWebsite.csproj, test/Microsoft.AspNetCore.Localization.FunctionalTests/TestRunner.cs, test/Microsoft.AspNetCore.Localization.Routing.Tests/Microsoft.AspNetCore.Localization.Routing.Tests.csproj, test/Microsoft.AspNetCore.Localization.Tests/Microsoft.AspNetCore.Localization.Tests.csproj, test/Microsoft.AspNetCore.Localization.Tests/RequestLocalizationOptionsTest.cs, test/Microsoft.Extensions.Localization.Tests/Microsoft.Extensions.Localization.Tests.csproj, test/ResourcesClassLibraryNoAttribute/ResourcesClassLibraryNoAttribute.csproj, test/ResourcesClassLibraryWithAttribute/ResourcesClassLibraryWithAttribute.csproj
- aspnet/Testing#248
- xUnit no longer supports .NET 4.5.1
- build tests for desktop .NET only on Windows
=> Bump test projects up to .NET 4.5.2

src/Microsoft.Extensions.Localization.Abstractions/LocalizedString.cs, src/Microsoft.Extensions.Localization/Internal/ResourceManagerStringLocalizerLoggerExtensions.cs, src/Microsoft.Extensions.Localization/Microsoft.Extensions.Localization.csproj, src/Microsoft.Extensions.Localization/ResourceManagerStringLocalizer.cs, src/Microsoft.Extensions.Localization/ResourceManagerStringLocalizerFactory.cs, src/Microsoft.Extensions.Localization/ResourceManagerWithCultureStringLocalizer.cs, test/Microsoft.AspNetCore.Localization.Tests/Microsoft.AspNetCore.Localization.Tests.csproj, test/Microsoft.Extensions.Localization.Tests/Microsoft.Extensions.Localization.Tests.csproj, test/Microsoft.Extensions.Localization.Tests/ResourceManagerStringLocalizerFactoryTest.cs, test/Microsoft.Extensions.Localization.Tests/ResourceManagerStringLocalizerTest.cs
=> Log diagnostic info about search for localization resources

samples/LocalizationSample/LocalizationSample.csproj, test/LocalizationWebsite/LocalizationWebsite.csproj
The runtime Ids should be removed from .csproj web projects while https://github.com/dotnet/sdk/issues/396 is got fixed
=> Remove RuntimeIdentifier from web projects

src/Microsoft.Extensions.Localization/ResourceManagerStringLocalizerFactory.cs, src/Microsoft.Extensions.Localization/RootNamespaceAttribute.cs, test/Microsoft.Extensions.Localization.Tests/ResourceManagerStringLocalizerFactoryTest.cs, test/ResourcesClassLibraryWithAttribute/AssemblyInfo.cs, test/ResourcesClassLibraryWithAttribute/ResourcesClassLibraryWithAttribute.csproj
This fixes the problem of us lacking a RootNamespace at runtime. I've made it a separate attribute so that when we create it using a task in the future people won't have to worry about the task interfeering with their `ResourceLocationAttribute`.
=> Allow setting RootNamespace in ResourceLocationAttribute

build/dependencies.props, korebuild-lock.txt, test/Microsoft.Extensions.Localization.Tests/LocalizationServiceCollectionExtensionsTest.cs
Since these tests counted services they failed when Options added more services. I converted them to follow the same pattern we use [here](https://github.com/aspnet/Mvc/blob/f75267faee58bbc1b6d87393ad4b9c57bfafaa4f/test/Microsoft.AspNetCore.Mvc.Localization.Test/Internal/MvcLocalizationServiceCollectionExtensionsTest.cs) and avoid making assumptions about what options does.
=> Fix tests broken by changes to config
