- samples/LocalizationSample/Startup.cs
- src/Microsoft.Framework.Localization.Abstractions/IStringLocalizerOfT.cs
- src/Microsoft.Framework.Localization/ResourceManagerStringLocalizer.cs
Remove unnecessary directives from LocalizationSample and Localization source
/cc @DamianEdwards
> Unnecessary using directives

- src/Microsoft.Framework.Localization/project.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/aspnet/localization/29)
> Move System.Resources.ReaderWriter to dnxcore50 node

- test/Microsoft.Framework.Localization.Test/project.json
/cc @davidfowl @DamianEdwards @Eilon @muratg
> return to the official xunit build

- src/CultureInfoGenerator/project.json
- src/Microsoft.AspNet.Localization/project.json
- src/Microsoft.Framework.Globalization.CultureInfoCache/project.json
- src/Microsoft.Framework.Localization.Abstractions/project.json
- src/Microsoft.Framework.Localization/project.json
> Added repository information to project.json files

- src/Microsoft.AspNet.Localization/QueryStringRequestCultureProvider.cs
Based on issue #62 I made this PR
> Fix 'QueryStringRequestCultureProvider' Issue

- src/Microsoft.AspNet.Localization/AcceptLanguageHeaderRequestCultureProvider.cs
- test/Microsoft.AspNet.Localization.Tests/AccessLanguageHeaderRequestCultureProviderTest.cs
> Fix for #38: Fallback to wrong language preference when the top preference is unavailable

- samples/LocalizationSample/Startup.cs
- samples/LocalizationSample/Startup.es-ES.resx
- samples/LocalizationSample/Startup.fr-FR.resx
- samples/LocalizationSample/Startup.ja-JP.resx
- samples/LocalizationSample/Startup.zh-CN.resx
- samples/LocalizationSample/Startup.zh.resx
> fix #3: Add localized resources to the sample

- NuGetPackageVerifier.json
> Remove CultureInfoGenerator from NugetPackageVerifier

- .travis.yml
/cc @cesarbs @kirthik @DamianEdwards
> Update .travis.yml to install libuv

- src/Microsoft.AspNet.Localization/RequestLocalizationOptions.cs
- test/Microsoft.AspNet.Localization.Tests/Microsoft.AspNet.Localization.Tests.xproj
- build break
nit: let VS have its way w/ a `.xproj` file
> Remove `[SuppressMessage]`s

- src/Microsoft.AspNet.Localization/RequestLocalizationMiddleware.cs
- src/Microsoft.Extensions.Localization.Abstractions/IStringLocalizer.cs
- src/Microsoft.Extensions.Localization.Abstractions/LocalizedString.cs
- src/Microsoft.Extensions.Localization.Abstractions/StringLocalizerExtensions.cs
- src/Microsoft.Extensions.Localization.Abstractions/StringLocalizerOfT.cs
- src/Microsoft.Extensions.Localization/ResourceManagerStringLocalizer.cs
- src/Microsoft.Extensions.Localization/ResourceManagerWithCultureStringLocalizer.cs
> Rename "ancestor" to "parent" on loc APIs

- src/Microsoft.Extensions.Localization.Abstractions/LocalizedString.cs
> Don't throw if LocalizedString is null

- src/Microsoft.Extensions.Localization/ResourceManagerStringLocalizerFactory.cs
- test/Microsoft.Extensions.Localization.Tests/ResourceManagerStringLocalizerFactoryTest.cs
- test/Microsoft.Extensions.Localization.Tests/project.json
- Cleaned up code a little to make it easier to understand (maybe)
- #138 
@ryanbrandenburg  @rynowak
> Tweaked cache key when getting localizer from basName/location:

- samples/LocalizationSample/Startup.cs
- samples/LocalizationSample/hosting.json
- samples/LocalizationSample/project.json
- test/Microsoft.AspNet.Localization.Tests/AcceptLanguageHeaderRequestCultureProviderTest.cs
- test/Microsoft.AspNet.Localization.Tests/CookieRequestCultureProviderTest.cs
- test/Microsoft.AspNet.Localization.Tests/CustomRequestCultureProviderTest.cs
- test/Microsoft.AspNet.Localization.Tests/QueryStringRequestCultureProviderTest.cs
Reacting to https://github.com/aspnet/Hosting/pull/521
> Reacting to new Hosting API

- samples/LocalizationSample/Startup.cs
- src/Microsoft.AspNet.Localization/ApplicationBuilderExtensions.cs
- test/LocalizationWebsite/StartupResourcesAtRootFolder.cs
- test/LocalizationWebsite/StartupResourcesInFolder.cs
- test/Microsoft.AspNet.Localization.Tests/AcceptLanguageHeaderRequestCultureProviderTest.cs
- test/Microsoft.AspNet.Localization.Tests/CookieRequestCultureProviderTest.cs
- test/Microsoft.AspNet.Localization.Tests/CustomRequestCultureProviderTest.cs
- test/Microsoft.AspNet.Localization.Tests/QueryStringRequestCultureProviderTest.cs
Standardizing ConfigureOptions to lambda https://github.com/aspnet/Coherence-Signed/issues/144
> Standardizing middleware to use configureOptions lambda

- test/Microsoft.Extensions.Localization.Tests/ResourceManagerStringLocalizerTest.cs
Should fix a problem we were having on CI where the culture was "en_POSIX" instead of "en_US".
>  * Make test culture independent

- samples/LocalizationSample/Startup.cs
- src/Microsoft.AspNet.Localization/ApplicationBuilderExtensions.cs
- src/Microsoft.AspNet.Localization/RequestCultureProvider.cs
- src/Microsoft.AspNet.Localization/RequestLocalizationMiddleware.cs
- src/Microsoft.AspNet.Localization/RequestLocalizationOptions.cs
- src/Microsoft.AspNet.Localization/project.json
- src/Microsoft.Extensions.Localization/LocalizationServiceCollectionExtensions.cs
- test/LocalizationWebsite/StartupResourcesAtRootFolder.cs
- test/LocalizationWebsite/StartupResourcesInFolder.cs
- test/Microsoft.AspNet.Localization.Tests/AcceptLanguageHeaderRequestCultureProviderTest.cs
- test/Microsoft.AspNet.Localization.Tests/CookieRequestCultureProviderTest.cs
- test/Microsoft.AspNet.Localization.Tests/CustomRequestCultureProviderTest.cs
- test/Microsoft.AspNet.Localization.Tests/QueryStringRequestCultureProviderTest.cs
- test/Microsoft.AspNet.Localization.Tests/RequestLocalizationOptionsTest.cs
- test/Microsoft.Extensions.Localization.Tests/LocalizationServiceCollectionExtensionsTest.cs
https://github.com/aspnet/Options/issues/105
> Updating to new options pattern

- src/Microsoft.Extensions.Localization/project.json
- test/Microsoft.Extensions.Localization.Tests/project.json
>  * Replace System.Resources.ReaderWriter

- samples/LocalizationSample/Startup.cs
> Update localization sample and make it cli-ready

- test/Microsoft.AspNetCore.Localization.FunctionalTests/project.json
- test/Microsoft.AspNetCore.Localization.Tests/project.json
- test/Microsoft.Extensions.Localization.Tests/project.json
> Reference Microsoft.NETCore.Platforms where necessary.

- NuGetPackageVerifier.json
- src/Microsoft.AspNetCore.Localization/IRequestCultureFeature.cs
- src/Microsoft.AspNetCore.Localization/project.json
- src/Microsoft.Extensions.Globalization.CultureInfoCache/project.json
- src/Microsoft.Extensions.Localization.Abstractions/IStringLocalizer.cs
- src/Microsoft.Extensions.Localization.Abstractions/IStringLocalizerOfT.cs
- src/Microsoft.Extensions.Localization.Abstractions/StringLocalizerOfT.cs
- src/Microsoft.Extensions.Localization.Abstractions/project.json
- src/Microsoft.Extensions.Localization/project.json
> Enabled xml doc generation

- src/Microsoft.Extensions.Localization/LocalizationServiceCollectionExtensions.cs
- test/Microsoft.Extensions.Localization.Tests/LocalizationServiceCollectionExtensionsTest.cs
> Fix test failures

- src/Microsoft.AspNetCore.Localization/CookieRequestCultureProvider.cs
- test/Microsoft.AspNetCore.Localization.FunctionalTests/TestRunner.cs
- test/Microsoft.AspNetCore.Localization.FunctionalTests/project.json
> Update cookie name

- src/Microsoft.AspNetCore.Localization/project.json
- src/Microsoft.Extensions.Globalization.CultureInfoCache/project.json
- src/Microsoft.Extensions.Localization.Abstractions/project.json
- src/Microsoft.Extensions.Localization/project.json
@ryanbrandenburg @DamianEdwards
> Fix package metadata

- samples/LocalizationSample/project.json
- test/Microsoft.AspNetCore.Localization.FunctionalTests/TestRunner.cs
@Tratcher @ryanbrandenburg @pranavkm
> Fixing sample for tests

- test/Microsoft.AspNetCore.Localization.FunctionalTests/Properties/AssemblyInfo.cs
@Tratcher @JunTaoLuo 
Should stop the Loc tests from failing on CI
> Functional tests run serially

- samples/LocalizationSample/Startup.cs
- samples/LocalizationSample/project.json
- samples/LocalizationSample/web.config
- samples/LocalizationSample/wwwroot/web.config
- test/LocalizationWebsite/project.json
- test/LocalizationWebsite/wwwroot/web.config
Review: @Tratcher 
RC2 Approval: @Eilon @DamianEdwards
> Move web.config and use ANCM

- samples/LocalizationSample/Startup.cs
- samples/LocalizationSample/project.json
- test/LocalizationWebsite/project.json
- test/Microsoft.AspNetCore.Localization.FunctionalTests/project.json
- test/Microsoft.AspNetCore.Localization.Tests/project.json
- test/Microsoft.Extensions.Localization.Tests/project.json
> Migrate tests/samples/tools to portable

- samples/LocalizationSample/project.json
- samples/LocalizationSample/web.config
> Update web.config and add publish tool

- test/Microsoft.AspNetCore.Localization.FunctionalTests/LocalizationSampleTest.cs
cc @BrennanConroy @cesarbs 
Approval: @Eilon
> Disable tests failing on CLR on Linux and Mac

- .gitignore
- Localization.sln
- samples/LocalizationSample/Startup.cs
- src/Microsoft.Extensions.Localization/ResourceManagerStringLocalizerFactory.cs
If everyone's ok with the general shape of things here I'll move `ClassLibraryResourceManagerStringLocalizerFactory.cs` into the Entropy repo and give it a sample.
> An example ResourceManagerStringLocalizerFactory which uses libraries

- test/Microsoft.AspNetCore.Localization.FunctionalTests/project.json
Follow up to https://github.com/aspnet/Hosting/pull/841
> Fix pinning of Microsoft.AspNetCore.Server.Testing

- Localization.sln
- src/Microsoft.Extensions.Localization/ResourceLocationAttribute.cs
- src/Microsoft.Extensions.Localization/ResourceManagerStringLocalizerFactory.cs
- src/Microsoft.Extensions.Localization/project.json
- test/LocalizationWebsite/StartupResourcesInClassLibrary.cs
- test/LocalizationWebsite/StartupResourcesInFolder.cs
- test/LocalizationWebsite/project.json
- test/Microsoft.AspNetCore.Localization.FunctionalTests/LocalizationTest.cs
- test/Microsoft.Extensions.Localization.Tests/ResourceManagerStringLocalizerFactoryTest.cs
- test/ResourcesClassLibraryNoAttribute/Model.cs
- test/ResourcesClassLibraryNoAttribute/Properties/AssemblyInfo.cs
- test/ResourcesClassLibraryNoAttribute/Resources/Model.resx
- test/ResourcesClassLibraryNoAttribute/project.json
- test/ResourcesClassLibraryWithAttribute/Model.cs
- test/ResourcesClassLibraryWithAttribute/Properties/AssemblyInfo.cs
- test/ResourcesClassLibraryWithAttribute/ResourceFolder/Model.resx
- test/ResourcesClassLibraryWithAttribute/project.json
This should allow localization to find resources in a class library by using an Assembly attribute to note the location of the resources folder.
> Class library resources

- test/Microsoft.AspNetCore.Localization.FunctionalTests/LocalizationSampleTest.cs
- test/Microsoft.AspNetCore.Localization.FunctionalTests/LocalizationTest.cs
Fixes #284. Standardize and de-duplicate functional tests.
> Organize Functional tests

- samples/LocalizationSample/Startup.cs
- src/Microsoft.AspNetCore.Localization/RequestCultureProvider.cs
- src/Microsoft.AspNetCore.Localization/RequestLocalizationMiddleware.cs
- src/Microsoft.Extensions.Localization.Abstractions/StringLocalizerOfT.cs
- src/Microsoft.Extensions.Localization/Internal/AssemblyResourceStringProvider.cs
- src/Microsoft.Extensions.Localization/ResourceManagerStringLocalizer.cs
- src/Microsoft.Extensions.Localization/ResourceManagerWithCultureStringLocalizer.cs
- test/LocalizationWebsite/Models/Customer.cs
- test/Microsoft.AspNetCore.Localization.FunctionalTests/LocalizationSampleTest.cs
- test/Microsoft.AspNetCore.Localization.FunctionalTests/LocalizationTest.cs
- test/Microsoft.AspNetCore.Localization.Routing.Tests/RouteDataRequestCultureProviderTest.cs
- test/Microsoft.AspNetCore.Localization.Tests/AcceptLanguageHeaderRequestCultureProviderTest.cs
- test/Microsoft.AspNetCore.Localization.Tests/CookieRequestCultureProviderTest.cs
- test/Microsoft.AspNetCore.Localization.Tests/QueryStringRequestCultureProviderTest.cs
- test/Microsoft.Extensions.Localization.Tests/ResourceManagerStringLocalizerTest.cs
Bunch of minor fixes including:
- Add necessary lines
- Remove unnecessary white space
- Add Copyrights
- Remove unnecessary packages
/cc @ryanbrandenburg
> Minor Fixes

- test/Microsoft.AspNetCore.Localization.FunctionalTests/LocalizationSampleTest.cs
- test/Microsoft.AspNetCore.Localization.FunctionalTests/LocalizationTest.cs
Disabling tests until https://github.com/dotnet/cli/issues/5172 is resolved.
Tracking work item to re-enable tests: https://github.com/aspnet/Localization/issues/310
> Temporarily skip tests

- src/Microsoft.Extensions.Localization/ResourceManagerStringLocalizerFactory.cs
- src/Microsoft.Extensions.Localization/exceptions.net45.json
- src/Microsoft.Extensions.Localization/exceptions.netcore.json
- src/Microsoft.Extensions.Localization/project.json
- test/Microsoft.Extensions.Localization.Tests/ResourceManagerStringLocalizerFactoryTest.cs
This removes the dependency on `Microsoft.AspNetCore.Hosting.Abstractions`.
> Remove dependency on Hosting.Abstractions

- test/LocalizationWebsite/StartupResourcesAtRootFolder.cs
- test/LocalizationWebsite/StartupResourcesInFolder.cs
- test/Microsoft.AspNetCore.Localization.FunctionalTests/LocalizationTest.cs
> Fix StringLocalizer location null tests

- test/Microsoft.AspNetCore.Localization.FunctionalTests/LocalizationSampleTest.cs
- test/Microsoft.AspNetCore.Localization.FunctionalTests/LocalizationTest.cs
> Unskip tests

- test/LocalizationWebsite/LocalizationWebsite.csproj
- test/LocalizationWebsite/Resources/StartupCustomCulturePreserved.en-US.resx
- test/LocalizationWebsite/StartupResourcesInFolder.cs
- test/Microsoft.AspNetCore.Localization.FunctionalTests/LocalizationTest.cs
> English does not override

- test/Microsoft.Extensions.Localization.Tests/Microsoft.Extensions.Localization.Tests.csproj
- test/Microsoft.Extensions.Localization.Tests/ResourceManagerStringLocalizerFactoryTest.cs
> Using NullLogger types from Logging.Abstractions

- test/Microsoft.Extensions.Localization.Tests/Microsoft.Extensions.Localization.Tests.csproj
> Fix build break

- .gitignore
- build/dependencies.props
- samples/LocalizationSample/LocalizationSample.csproj
- samples/LocalizationSample/Startup.cs
- src/Microsoft.AspNetCore.Localization.Routing/Microsoft.AspNetCore.Localization.Routing.csproj
- src/Microsoft.AspNetCore.Localization/Microsoft.AspNetCore.Localization.csproj
- src/Microsoft.AspNetCore.Localization/RequestLocalizationMiddleware.cs
- src/Microsoft.Extensions.Localization/Microsoft.Extensions.Localization.csproj
- test/LocalizationWebsite/LocalizationWebsite.csproj
- test/Microsoft.AspNetCore.Localization.FunctionalTests/Microsoft.AspNetCore.Localization.FunctionalTests.csproj
- test/Microsoft.AspNetCore.Localization.FunctionalTests/TestRunner.cs
- test/Microsoft.AspNetCore.Localization.Routing.Tests/Microsoft.AspNetCore.Localization.Routing.Tests.csproj
- test/Microsoft.AspNetCore.Localization.Tests/Microsoft.AspNetCore.Localization.Tests.csproj
- test/Microsoft.AspNetCore.Localization.Tests/RequestLocalizationOptionsTest.cs
- test/Microsoft.Extensions.Localization.Tests/Microsoft.Extensions.Localization.Tests.csproj
- test/ResourcesClassLibraryNoAttribute/ResourcesClassLibraryNoAttribute.csproj
- test/ResourcesClassLibraryWithAttribute/ResourcesClassLibraryWithAttribute.csproj
* Remove net451 as a compilation target
* Upgrade to netcoreapp2.0
> Change compilation targets.

- NuGet.config
- test/Microsoft.AspNetCore.Localization.FunctionalTests/Microsoft.AspNetCore.Localization.FunctionalTests.csproj
- test/Microsoft.AspNetCore.Localization.FunctionalTests/TestRunner.cs
This PR removes all references to PlatformAbstractions.
Part of aspnet/PlatformAbstractions#50
> react to removal of PlatformAbstractions

- test/Microsoft.AspNetCore.Localization.FunctionalTests/LocalizationSampleTest.cs
- test/Microsoft.AspNetCore.Localization.FunctionalTests/LocalizationTest.cs
- test/Microsoft.AspNetCore.Localization.FunctionalTests/TestRunner.cs
> Automatically allocate ports for functional tests

- test/LocalizationWebsite/Program.cs
- test/LocalizationWebsite/StartupResourcesAtRootFolder.cs
- test/LocalizationWebsite/StartupResourcesInClassLibrary.cs
- test/LocalizationWebsite/StartupResourcesInFolder.cs
> React to Logging API changes

- test/Microsoft.Extensions.Localization.Tests/Microsoft.Extensions.Localization.Tests.csproj
https://github.com/aspnet/Coherence/issues/175
> Remove unnecessary package references

- src/Microsoft.AspNetCore.Localization/ProviderCultureResult.cs
- src/Microsoft.AspNetCore.Localization/RequestLocalizationMiddleware.cs
- src/Microsoft.AspNetCore.Localization/breakingchanges.netcore.json
https://github.com/aspnet/HttpAbstractions/pull/844
> React to StringSegment header parsers

- build/dependencies.props
- src/Microsoft.Extensions.Localization.Abstractions/Microsoft.Extensions.Localization.Abstractions.csproj
- src/Microsoft.Extensions.Localization/Microsoft.Extensions.Localization.csproj
- test/ResourcesClassLibraryNoAttribute/ResourcesClassLibraryNoAttribute.csproj
- test/ResourcesClassLibraryWithAttribute/ResourcesClassLibraryWithAttribute.csproj
Part of https://github.com/aspnet/Home/issues/2045
> Target .NET Standard 2.0

- README.md
> Reference `Entropy` localization samples

- src/Microsoft.Extensions.Localization/ResourceManagerWithCultureStringLocalizer.cs
> Fix issue #421

- test/Microsoft.AspNetCore.Localization.Tests/CookieRequestCultureProviderTest.cs
Preparing for aspnet/Logging#804
> Update usage of TestSink

- README.md
I have updated the hyperlink for README.md in target branch of release/2.2 as 
reference to https://github.com/aspnet/Localization/pull/452
> Update hyperlink for README.md in release/2.2

- samples/LocalizationSample/Startup.cs
- src/Microsoft.AspNetCore.Localization/RequestLocalizationOptionsExtensions.cs
- test/Microsoft.AspNetCore.Localization.Tests/RequestLocalizationOptionsExtensionsTest.cs
Fixes https://github.com/aspnet/AspNetCore/issues/3336
> Adding AddRequestCultureProvider as extension method
